### ISSUE TITLE
Excellent.. small request

### ISSUE THREAD

**Issue by tvld** [aterenin/right-click-external-app#1]
It works excellent on my Ubuntu 17.10. However, for an image for example, the external is the default viewer, set in the OS.

I would like to open an editor; would a configuration be possible?

**Comment by aterenin** [comment]
For the sake of keeping this plugin ultra simple and lightweight, I prefer not to add more features to the published version - but don't worry, you can easily modify the source to do that! The relevant line is in `lib/right-click-external-app.coffee` is `shell.openItem(filePath)`. 

Unfortunately, from the documentation in `https://github.com/electron/electron/blob/master/docs/api/shell.md` there appears to not be a way to open items in a different application using that API, so you'd to find an API that can open the application for you, probably by running a terminal command. Then, just replace `shell.openItem(filePath)` with an if statement that either executes the command for your extension, or the original one.

Note that Atom will let you install plugins by copy/pasting a Git repository URL, so you can just fork this repo and easily install that version on any systems you like. Hope this helps!
